/* Generated by Nim Compiler v0.18.0 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w -O3 -fno-strict-aliasing  -I/home/lmariscal/.choosenim/toolchains/nim-0.18.0/lib -o /home/lmariscal/dev/nimcr/nimcache/nimcr_nimcr.o /home/lmariscal/dev/nimcr/nimcache/nimcr_nimcr.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg tyTuple_7q7q3E6Oj24ZNVJb9aonhAg;
typedef struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA;
typedef struct tyTuple_XOVT24GHXwqiEj5GCsEGCA tyTuple_XOVT24GHXwqiEj5GCsEGCA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyTuple_7q7q3E6Oj24ZNVJb9aonhAg {
NimStringDesc* Field0;
NimStringDesc* Field1;
NimStringDesc* Field2;
};
struct tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA {
NI a;
NI b;
};
struct tyTuple_XOVT24GHXwqiEj5GCsEGCA {
NimStringDesc* Field0;
NI Field1;
};
typedef NU8 tySet_tyEnum_ProcessOption_bnU6W8LhTMnT4JaSWtGlSA;
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ)(void);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NIMCALL(void, write_c4mGyJBvK73pdM22jiweKQ)(FILE* f, NimStringDesc* s);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_4)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosexpandFilename)(NimStringDesc* filename);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_5)(void);
N_LIB_PRIVATE N_NIMCALL(void, nossplitFile)(NimStringDesc* path, tyTuple_7q7q3E6Oj24ZNVJb9aonhAg* Result);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_6)(void);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_8)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, slash__lXoMhn1ZYc9cAJa9bfA61msg)(NimStringDesc* head, NimStringDesc* tail);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_10)(void);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_11)(void);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_12)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nsuJoinSep)(NimStringDesc** a, NI aLen_0, NimStringDesc* sep);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg)(NimStringDesc** s, NI sLen_0, tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA x);
static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qnimcr)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, nosfileNewer)(NimStringDesc* a, NimStringDesc* b);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_14)(void);
N_LIB_PRIVATE N_NIMCALL(void, nosremoveFile)(NimStringDesc* file);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, nosgetTempDir)(void);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, toHex_RWt8eOlEO1IrZycSUh7tPg)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_21)(void);
N_LIB_PRIVATE N_NIMCALL(void, execCmdEx_bITTGyMXZwwEXI9blfpV4cg)(NimStringDesc* command, tySet_tyEnum_ProcessOption_bnU6W8LhTMnT4JaSWtGlSA options, tyTuple_XOVT24GHXwqiEj5GCsEGCA* Result);
N_LIB_PRIVATE N_NIMCALL(NI, nosexecShellCmd)(NimStringDesc* command);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strtabsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_linuxDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_cpuinfoDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osprocDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, nimcrDatInit000)(void);
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* args_MOYq76YvflDi9cCuIbA6qAw;
extern TNimType NTI_sM4lkSb7zS6F7OVMvW9cffQ_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
NimStringDesc* filename_UuHdM9cJsc9br1hrXusE9aS0w;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
tyTuple_7q7q3E6Oj24ZNVJb9aonhAg splitName_yE4QD8bmEqfraszlS8Yhrw;
extern TNimType NTI_7q7q3E6Oj24ZNVJb9aonhAg_;
NimStringDesc* ext_V0OV4GSmQPNpiA33E0PPbg;
NimStringDesc* exeName_NYBBzqne6W9bRZcQY49cS0PA;
NI buildStatus_Df4A5godQtBeIZrpVR4oKQ;
NimStringDesc* output_yVJrMwR9bYWOKnPM7ydqddQ;
NimStringDesc* command_Cu9b0UTeP3Yq6qmxrd7VrEw;
NimStringDesc* argsExe_Y7Fqa1mbvvhPaaDglfQ68w;
NimStringDesc* extraArgs_1agJqLkwczcUfLza9abQZFg;
tyTuple_XOVT24GHXwqiEj5GCsEGCA __cuuUVZZISV4CMjTQ79apr2Q;
extern TNimType NTI_XOVT24GHXwqiEj5GCsEGCA_;
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_3, "Usage: nimcr filename [compile target, default \'c\' [options]]", 61);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_7, "", 0);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_9, ".", 1);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_13, " ", 1);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_15, "c", 1);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_16, "nim ", 4);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_17, " --colors:on --nimcache:", 24);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_18, "nimcache-", 9);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_19, " -d:release --out:\"", 19);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_20, "\" ", 2);
STRING_LITERAL(TM_S9csiPnKvgoeDK7IKYFbtSg_22, "(nimcr) Error on build running command: ", 40);
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_2)(void) {
	nimGCvisit((void*)args_MOYq76YvflDi9cCuIbA6qAw, 0);
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		if (!!((src == NIM_NIL))) goto LA3_;
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	(*dest) = src;
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_4)(void) {
	nimGCvisit((void*)filename_UuHdM9cJsc9br1hrXusE9aS0w, 0);
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_5)(void) {
	nimGCvisit((void*)splitName_yE4QD8bmEqfraszlS8Yhrw.Field0, 0);
	nimGCvisit((void*)splitName_yE4QD8bmEqfraszlS8Yhrw.Field1, 0);
	nimGCvisit((void*)splitName_yE4QD8bmEqfraszlS8Yhrw.Field2, 0);
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_6)(void) {
	nimGCvisit((void*)ext_V0OV4GSmQPNpiA33E0PPbg, 0);
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_8)(void) {
	nimGCvisit((void*)exeName_NYBBzqne6W9bRZcQY49cS0PA, 0);
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_10)(void) {
	nimGCvisit((void*)output_yVJrMwR9bYWOKnPM7ydqddQ, 0);
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_11)(void) {
	nimGCvisit((void*)command_Cu9b0UTeP3Yq6qmxrd7VrEw, 0);
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_12)(void) {
	nimGCvisit((void*)argsExe_Y7Fqa1mbvvhPaaDglfQ68w, 0);
}

static N_INLINE(tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA, dotdot__vDQySKWzgnxQdUarow6k5Qnimcr)(NI a, NI b) {
	tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA result;
	memset((void*)(&result), 0, sizeof(result));
	result.a = a;
	result.b = b;
	return result;
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_14)(void) {
	nimGCvisit((void*)extraArgs_1agJqLkwczcUfLza9abQZFg, 0);
}
static N_NIMCALL(void, TM_S9csiPnKvgoeDK7IKYFbtSg_21)(void) {
	nimGCvisit((void*)__cuuUVZZISV4CMjTQ79apr2Q.Field0, 0);
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_posixDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	stdlib_hashesDatInit000();
	stdlib_strtabsDatInit000();
	stdlib_streamsDatInit000();
	stdlib_linuxDatInit000();
	stdlib_cpuinfoDatInit000();
	stdlib_osprocDatInit000();
	nimcrDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_posixInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	stdlib_hashesInit000();
	stdlib_strtabsInit000();
	stdlib_streamsInit000();
	stdlib_linuxInit000();
	stdlib_cpuinfoInit000();
	stdlib_osprocInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	NimStringDesc* T6_;
	NimStringDesc* T7_;
	NimStringDesc* T8_;
	NimStringDesc* T9_;
	NimStringDesc* T10_;
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_2);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_4);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_5);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_6);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_8);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_10);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_11);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_12);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_14);
nimRegisterGlobalMarker(TM_S9csiPnKvgoeDK7IKYFbtSg_21);
	asgnRefNoCycle((void**) (&args_MOYq76YvflDi9cCuIbA6qAw), commandLineParams_WoBZMy8AVRATRE9bQuYWzCQ());
	{
		NI T3_;
		T3_ = (args_MOYq76YvflDi9cCuIbA6qAw ? args_MOYq76YvflDi9cCuIbA6qAw->Sup.len : 0);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		write_c4mGyJBvK73pdM22jiweKQ(stderr, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_3));
		exit(((NI) -1));
	}
	LA4_: ;
	asgnRefNoCycle((void**) (&filename_UuHdM9cJsc9br1hrXusE9aS0w), nosexpandFilename(args_MOYq76YvflDi9cCuIbA6qAw->data[((NI) 0)]));
	nossplitFile(filename_UuHdM9cJsc9br1hrXusE9aS0w, (&splitName_yE4QD8bmEqfraszlS8Yhrw));
	T6_ = (NimStringDesc*)0;
	T6_ = ext_V0OV4GSmQPNpiA33E0PPbg; ext_V0OV4GSmQPNpiA33E0PPbg = copyStringRC1(((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_7));
	if (T6_) nimGCunrefNoCycle(T6_);
	T7_ = (NimStringDesc*)0;
	T7_ = rawNewString(splitName_yE4QD8bmEqfraszlS8Yhrw.Field1->Sup.len + ext_V0OV4GSmQPNpiA33E0PPbg->Sup.len + 1);
appendString(T7_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_9));
appendString(T7_, splitName_yE4QD8bmEqfraszlS8Yhrw.Field1);
appendString(T7_, ext_V0OV4GSmQPNpiA33E0PPbg);
	asgnRefNoCycle((void**) (&exeName_NYBBzqne6W9bRZcQY49cS0PA), slash__lXoMhn1ZYc9cAJa9bfA61msg(splitName_yE4QD8bmEqfraszlS8Yhrw.Field0, T7_));
	buildStatus_Df4A5godQtBeIZrpVR4oKQ = ((NI) 0);
	T8_ = (NimStringDesc*)0;
	T8_ = output_yVJrMwR9bYWOKnPM7ydqddQ; output_yVJrMwR9bYWOKnPM7ydqddQ = copyStringRC1(((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_7));
	if (T8_) nimGCunrefNoCycle(T8_);
	T9_ = (NimStringDesc*)0;
	T9_ = command_Cu9b0UTeP3Yq6qmxrd7VrEw; command_Cu9b0UTeP3Yq6qmxrd7VrEw = copyStringRC1(((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_7));
	if (T9_) nimGCunrefNoCycle(T9_);
	T10_ = (NimStringDesc*)0;
	T10_ = argsExe_Y7Fqa1mbvvhPaaDglfQ68w; argsExe_Y7Fqa1mbvvhPaaDglfQ68w = copyStringRC1(((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_7));
	if (T10_) nimGCunrefNoCycle(T10_);
	{
		NI T13_;
		NI T16_;
		tyObject_HSlice_x7qpDivRIi6zcMSMsudNPA T17_;
		tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T18_;
		T13_ = (args_MOYq76YvflDi9cCuIbA6qAw ? args_MOYq76YvflDi9cCuIbA6qAw->Sup.len : 0);
		if (!(((NI) 1) < T13_)) goto LA14_;
		T16_ = (args_MOYq76YvflDi9cCuIbA6qAw ? args_MOYq76YvflDi9cCuIbA6qAw->Sup.len : 0);
		T17_ = dotdot__vDQySKWzgnxQdUarow6k5Qnimcr(((NI) 1), (NI)(T16_ - ((NI) 1)));
		T18_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
		T18_ = X5BX5D__9bjGtpdrVmRb5ws4GFWYQCg(args_MOYq76YvflDi9cCuIbA6qAw->data, args_MOYq76YvflDi9cCuIbA6qAw->Sup.len, T17_);
		asgnRefNoCycle((void**) (&argsExe_Y7Fqa1mbvvhPaaDglfQ68w), nsuJoinSep(T18_->data, T18_->Sup.len, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_13)));
	}
	LA14_: ;
	{
		NIM_BOOL T21_;
		NIM_BOOL T22_;
		NimStringDesc* T26_;
		NimStringDesc* T27_;
		NimStringDesc* T28_;
		NimStringDesc* T29_;
		NI T30_;
		NimStringDesc* T31_;
		NimStringDesc* T32_;
		NimStringDesc* T33_;
		T21_ = (NIM_BOOL)0;
		T22_ = (NIM_BOOL)0;
		T22_ = nosexistsFile(exeName_NYBBzqne6W9bRZcQY49cS0PA);
		T21_ = !(T22_);
		if (T21_) goto LA23_;
		T21_ = nosfileNewer(filename_UuHdM9cJsc9br1hrXusE9aS0w, exeName_NYBBzqne6W9bRZcQY49cS0PA);
		LA23_: ;
		if (!T21_) goto LA24_;
		T26_ = (NimStringDesc*)0;
		T26_ = extraArgs_1agJqLkwczcUfLza9abQZFg; extraArgs_1agJqLkwczcUfLza9abQZFg = copyStringRC1(((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_15));
		if (T26_) nimGCunrefNoCycle(T26_);
		nosremoveFile(exeName_NYBBzqne6W9bRZcQY49cS0PA);
		T27_ = (NimStringDesc*)0;
		T28_ = (NimStringDesc*)0;
		T28_ = nosgetTempDir();
		T29_ = (NimStringDesc*)0;
		T30_ = (NI)0;
		T30_ = hash_uBstFm5SYVQeOL3j9c9bc58A(filename_UuHdM9cJsc9br1hrXusE9aS0w);
		T31_ = (NimStringDesc*)0;
		T31_ = toHex_RWt8eOlEO1IrZycSUh7tPg(T30_);
		T29_ = rawNewString(T31_->Sup.len + 9);
appendString(T29_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_18));
appendString(T29_, T31_);
		T32_ = (NimStringDesc*)0;
		T32_ = slash__lXoMhn1ZYc9cAJa9bfA61msg(T28_, T29_);
		T27_ = rawNewString(extraArgs_1agJqLkwczcUfLza9abQZFg->Sup.len + T32_->Sup.len + exeName_NYBBzqne6W9bRZcQY49cS0PA->Sup.len + filename_UuHdM9cJsc9br1hrXusE9aS0w->Sup.len + 49);
appendString(T27_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_16));
appendString(T27_, extraArgs_1agJqLkwczcUfLza9abQZFg);
appendString(T27_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_17));
appendString(T27_, T32_);
appendString(T27_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_19));
appendString(T27_, exeName_NYBBzqne6W9bRZcQY49cS0PA);
appendString(T27_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_20));
appendString(T27_, filename_UuHdM9cJsc9br1hrXusE9aS0w);
		asgnRefNoCycle((void**) (&command_Cu9b0UTeP3Yq6qmxrd7VrEw), T27_);
		execCmdEx_bITTGyMXZwwEXI9blfpV4cg(command_Cu9b0UTeP3Yq6qmxrd7VrEw, 10, (&__cuuUVZZISV4CMjTQ79apr2Q));
		T33_ = (NimStringDesc*)0;
		T33_ = output_yVJrMwR9bYWOKnPM7ydqddQ; output_yVJrMwR9bYWOKnPM7ydqddQ = copyStringRC1(__cuuUVZZISV4CMjTQ79apr2Q.Field0);
		if (T33_) nimGCunrefNoCycle(T33_);
		buildStatus_Df4A5godQtBeIZrpVR4oKQ = __cuuUVZZISV4CMjTQ79apr2Q.Field1;
	}
	LA24_: ;
	{
		NimStringDesc* T38_;
		NI T39_;
		if (!(buildStatus_Df4A5godQtBeIZrpVR4oKQ == ((NI) 0))) goto LA36_;
		T38_ = (NimStringDesc*)0;
		T38_ = rawNewString(exeName_NYBBzqne6W9bRZcQY49cS0PA->Sup.len + argsExe_Y7Fqa1mbvvhPaaDglfQ68w->Sup.len + 1);
appendString(T38_, exeName_NYBBzqne6W9bRZcQY49cS0PA);
appendString(T38_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_13));
appendString(T38_, argsExe_Y7Fqa1mbvvhPaaDglfQ68w);
		T39_ = (NI)0;
		T39_ = nosexecShellCmd(T38_);
		exit(T39_);
	}
	goto LA34_;
	LA36_: ;
	{
		NimStringDesc* T41_;
		T41_ = (NimStringDesc*)0;
		T41_ = rawNewString(command_Cu9b0UTeP3Yq6qmxrd7VrEw->Sup.len + 40);
appendString(T41_, ((NimStringDesc*) &TM_S9csiPnKvgoeDK7IKYFbtSg_22));
appendString(T41_, command_Cu9b0UTeP3Yq6qmxrd7VrEw);
		write_c4mGyJBvK73pdM22jiweKQ(stderr, T41_);
		write_c4mGyJBvK73pdM22jiweKQ(stderr, output_yVJrMwR9bYWOKnPM7ydqddQ);
		exit(buildStatus_Df4A5godQtBeIZrpVR4oKQ);
	}
	LA34_: ;
}

NIM_EXTERNC N_NOINLINE(void, nimcrDatInit000)(void) {
}

